services:
  mongodb:
    image: mongo:7
    container_name: wtwt2-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: wtwt2

volumes:
  mongodb_data:
